### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [ttessarolo/safe-evaluate-expression#1]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by ttessarolo** [comment]
OK, done. Security policy is there.

**Comment by zidingz** [comment]
Hey @ttessarolo 

Thank you for adding a `SECURITY.md`!

Would there be an email we could reach you on? Our system produces a magic-link that give you privileges to view and validate the vulnerability on our advisory page, but I understand you may prefer for the issue to disclosed in public instead. Kindly let me know and I'll sort it for you.

Our security researchers may provide fixes too.  Simply ask via comments on our advisory page.

Let me know if you have further questions. Happy to help!
